<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-B5QH8RSV" ignored="0" name="InvalidSignup" tests="2" failures="1" timestamp="06 May 2020 08:58:05 GMT" time="34.198" errors="0">
  <testcase name="signUp2" time="9.965" classname="com.Appium.demo.Login.TC2_SignupInvalid"/>
  <testcase name="validateSignup" time="0.683" classname="com.Appium.demo.Login.TC2_SignupInvalid">
    <failure type="java.lang.AssertionError" message="expected [Please enter your name] but found [Please enter your name1]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your name] but found [Please enter your name1]
at com.Appium.demo.Login.TC2_SignupInvalid.validateSignup(TC2_SignupInvalid.java:69)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateSignup -->
</testsuite> <!-- InvalidSignup -->
